[env:seeed_xiao_esp32s3]
platform = espressif32 @ 6.13.0
board = seeed_xiao_esp32s3
framework = arduino
upload_speed = 460800
build_unflags =
    -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCFG_TUD_AUDIO=1
    -DCFG_TUD_AUDIO_FUNC_1_DESC_LEN=TUD_AUDIO_MIC_ONE_CH_DESC_LEN
    -DCFG_TUD_AUDIO_FUNC_1_N_AS_INT=1
    -DCFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ=64
    -DCFG_TUD_AUDIO_ENABLE_EP_IN=1
    -DCFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX=32
    -DCFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ=512
    -DCFG_TUD_AUDIO_EP_IN_FLOW_CONTROL=0
